
SELECT * FROM tb_cliente;

SELECT CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP,
DATA_NASCIMENTO, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM tb_cliente;

SELECT CPF, NOME FROM tb_cliente;

SELECT CPF, NOME FROM tb_cliente LIMIT 5;

SELECT CPF AS CPF_CLIENTE, NOME AS NOME_CLIENTE FROM tb_cliente;

SELECT NOME, CPF, SEXO, IDADE, DATA_NASCIMENTO FROM tb_cliente;
